import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { AppWrapper } from '@/containers/app-wrapper/AppWrapper';

const font = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />
      </head>
      <body className={font.className}>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
